window.COLABOURHOOD_PROJECTS = {
  "safer-crossing-ballinacurra-gardens": {
    title: "A safer crossing on Ballinacurra Gardens",
    status: "Gathering support",
    statusKey: "gathering",
    scope: "place",
    location: "Ballinacurra Gardens",
    lat: 52.64512,
    lng: -8.63546,
    organiser: "Aoife Murphy and 3 neighbours",
    objective: "Create a safer, clearer place for residents and children to cross.",
    description: "Residents have identified a busy point where parked cars and limited sightlines make crossing harder than it should be. This project will gather evidence, agree a practical design and organise the resources needed to deliver it safely.",
    why: "Children use this route on the way to school and neighbours cross here to reach local services. A clearer crossing point would make everyday journeys easier without waiting for a larger authority-led scheme.",
    neighbours: 34,
    supporters: ["Aoife M.", "Declan R.", "Niamh K.", "Sam O.", "Mary T.", "12 private supporters"],
    commitments: [
      ["21", "support the proposal"],
      ["6", "can volunteer"],
      ["2", "have relevant professional skills"],
      ["3", "tools or equipment offered"]
    ],
    funding: { pledged: 740, goal: 1200, received: 320, spent: 85 },
    expenses: [
      ["Road-marking measurement kit", "€45", "Receipt"],
      ["Printing and resident notices", "€40", "Receipt"]
    ],
    needs: [
      ["4 volunteers", "to record traffic and crossing patterns"],
      ["Road-safety knowledge", "to review the design options"],
      ["Measuring equipment", "for accurate dimensions"],
      ["Photography", "to document the current sightlines"]
    ],
    milestones: [
      ["complete", "Collect local observations", "Aoife and Declan", "Completed 18 June"],
      ["active", "Agree the preferred approach", "Project group", "Underway now"],
      ["next", "Confirm permissions and contractor requirements", "Niamh", "Target 5 July"],
      ["next", "Raise the shared budget", "Funding group", "Target 20 July"]
    ],
    updates: [
      ["22 June 2026", "Aoife Murphy", "Crossing observations completed", "Six volunteers recorded crossing and traffic patterns over three weekday periods.", "Observation summary.pdf"],
      ["19 June 2026", "Declan Ryan", "Three design options shared", "The project group added three low-cost options for neighbours to compare.", "Design options.pdf"],
      ["15 June 2026", "Niamh Kelly", "Contractor estimate added", "A local road-marking contractor supplied an indicative estimate for budgeting.", "Estimate.pdf"]
    ],
    media: ["crossing-street.png", "crossing-measurement.png", "crossing-sightline.png"]
  },
  "community-tool-library": {
    title: "Community tool library",
    status: "Ready to act",
    statusKey: "ready",
    scope: "place",
    location: "Near the community green",
    lat: 52.64637,
    lng: -8.63438,
    organiser: "Michael Byrne and 2 neighbours",
    objective: "Create a shared, bookable collection of useful household and garden tools.",
    description: "Neighbours can avoid buying rarely used equipment by pooling tools in a secure shared store with a simple booking and maintenance system.",
    why: "Shared tools save money, reduce waste and make small home and garden projects possible for more households.",
    neighbours: 21,
    supporters: ["Michael B.", "Róisín D.", "Pat H.", "4 private supporters"],
    commitments: [["15", "support the library"], ["5", "can volunteer"], ["8", "tools pledged"], ["2", "can help maintain equipment"]],
    funding: { pledged: 510, goal: 800, received: 260, spent: 60 },
    expenses: [["Heavy-duty storage shelves", "€60", "Receipt"]],
    needs: [["Secure storage", "a dry and accessible neighbourhood location"], ["Tool donations", "safe equipment in working order"], ["2 coordinators", "for monthly checks and bookings"]],
    milestones: [["complete", "Survey neighbour demand", "Michael", "Completed 12 June"], ["complete", "Draft lending rules", "Róisín", "Completed 17 June"], ["active", "Confirm storage location", "Project group", "Underway now"], ["next", "Open the first lending month", "Coordinators", "Target August"]],
    updates: [["21 June 2026", "Róisín Doyle", "Draft lending rules published", "Neighbours can now review the proposed booking and care rules.", "Lending rules.pdf"]],
    media: ["crossing-measurement.png", "crossing-street.png", "crossing-sightline.png"]
  },
  "spring-street-clean-up": {
    title: "Spring street clean-up",
    status: "Completed",
    statusKey: "completed",
    scope: "place",
    location: "Southern end of Ballinacurra Gardens",
    lat: 52.64389,
    lng: -8.63672,
    organiser: "Mary O'Donnell and 5 neighbours",
    objective: "Clear litter and improve the shared edges along the southern streets.",
    description: "A coordinated resident clean-up completed over one Saturday morning with shared tools, supplies and disposal.",
    why: "Small visible wins build confidence that neighbours can organise and care for shared places together.",
    neighbours: 46,
    supporters: ["Mary O.", "John F.", "Aisha K.", "18 private supporters"],
    commitments: [["46", "supported the action"], ["19", "volunteered"], ["12", "tools offered"], ["3", "vehicles helped"]],
    funding: { pledged: 285, goal: 250, received: 285, spent: 228 },
    expenses: [["Bags, gloves and litter pickers", "€128", "Receipt"], ["Waste collection", "€100", "Receipt"]],
    needs: [["2 stewards", "for a lighter monthly follow-up"], ["Storage space", "for the reusable litter pickers"]],
    milestones: [["complete", "Recruit volunteers", "Mary", "Completed"], ["complete", "Gather tools and supplies", "John", "Completed"], ["complete", "Run clean-up morning", "All volunteers", "Completed 11 May"], ["complete", "Publish spending and results", "Mary", "Completed"]],
    updates: [["12 May 2026", "Mary O'Donnell", "Clean-up completed", "Nineteen residents filled 31 bags and cleared three shared routes.", "Before and after photos"]],
    media: ["crossing-sightline.png", "crossing-street.png", "crossing-measurement.png"]
  },
  "play-space-for-younger-children": {
    title: "A play space for younger children",
    status: "Proposed",
    statusKey: "proposed",
    scope: "place",
    location: "The neighbourhood green",
    lat: 52.64682,
    lng: -8.63712,
    organiser: "Sarah Collins",
    objective: "Explore a modest, safe play area shaped by nearby families.",
    description: "Families are gathering ideas for a small play space suitable for younger children while preserving the green's open character.",
    why: "Parents currently travel outside the neighbourhood for simple play facilities and would value a nearby place to meet.",
    neighbours: 12,
    supporters: ["Sarah C.", "Tom L.", "5 private supporters"],
    commitments: [["12", "support exploring it"], ["4", "parents can help"], ["1", "landscape skill offered"], ["€180", "early pledges"]],
    funding: { pledged: 180, goal: 3500, received: 0, spent: 0 },
    expenses: [],
    needs: [["Family ideas", "what would be genuinely useful"], ["Design knowledge", "safe and inclusive play"], ["Cost research", "durable equipment options"]],
    milestones: [["active", "Gather family ideas", "Sarah", "Underway now"], ["next", "Sketch two possible layouts", "Design volunteers", "Next"], ["next", "Check consent and insurance", "Project group", "Next"], ["next", "Agree a funding target", "Project group", "Later"]],
    updates: [["20 June 2026", "Sarah Collins", "First family ideas collected", "Seven households shared the ages and types of play they would value.", "Ideas summary.pdf"]],
    media: ["crossing-street.png", "crossing-sightline.png", "crossing-measurement.png"]
  },
  "bulk-buy-home-energy-upgrades": {
    title: "Bulk-buy home energy upgrades",
    status: "Gathering support",
    statusKey: "gathering",
    scope: "neighbourhood",
    location: "Across Ballinacurra Gardens",
    organiser: "Eoin Walsh and 2 neighbours",
    objective: "Help interested households compare options and negotiate a better group price.",
    description: "This neighbourhood-wide project will pool demand, invite comparable installer quotes and share practical information on insulation and energy upgrades.",
    why: "Households face the same confusing choices individually. Acting together can reduce research, improve price transparency and create bargaining power.",
    neighbours: 18,
    supporters: ["Eoin W.", "Bríd N.", "Liam P.", "8 private supporters"],
    commitments: [["18", "households interested"], ["3", "can research grants"], ["2", "have building knowledge"], ["7", "want installer quotes"]],
    funding: { pledged: 0, goal: 0, received: 0, spent: 0 },
    expenses: [],
    needs: [["Household interest", "what upgrades people are considering"], ["Grant knowledge", "current eligibility and paperwork"], ["Installer contacts", "reputable firms willing to quote"]],
    milestones: [["active", "Survey interested households", "Eoin", "Underway now"], ["next", "Group homes by upgrade type", "Research team", "Next"], ["next", "Invite comparable quotes", "Project group", "Next"], ["next", "Share options with households", "Project group", "Later"]],
    updates: [["23 June 2026", "Eoin Walsh", "Household survey opened", "Residents can now register which upgrades they are considering without making a commitment.", "Household survey"]],
    media: ["crossing-street.png", "crossing-measurement.png", "crossing-sightline.png"]
  }
};
